Album.create("name"=>"Sgt. Pepper's Lonely Hearts Club Band", "release_year"=>1967)
Album.create("name"=>"Pet Sounds", "release_year"=>1966)
Album.create("name"=>"Revolver", "release_year"=>1966)
Album.create("name"=>"Highway 61 Revisited", "release_year"=>1965)
Album.create("name"=>"Rubber Soul", "release_year"=>1965)
Album.create("name"=>"What's Going On", "release_year"=>1971)
Album.create("name"=>"Exile on Main St.", "release_year"=>1972)
Album.create("name"=>"London Calling", "release_year"=>1979)
Album.create("name"=>"Blonde on Blonde", "release_year"=>1966)
Album.create("name"=>"The Beatles", "release_year"=>1968)
